### ISSUE TITLE
TFSectionDescriptor footerClass support + sectionClass renaming

### ISSUE THREAD

**Issue by jakubknejzlik** [thefuntasty/TFTableDescriptor#5]
Add support for footerView in TFSectionDescriptor (e.g. footerClass). Also sectionClass should be renamed to headerClass

**Comment by kafejo** [comment]
The common pattern there is rowClass for rows and sectionClass for sections. If you think that sectionClass should be named headerClass then rowClass should be also renamed to cellClass.

**Comment by jakubknejzlik** [comment]
Ah, I see. What about sectionHeaderClass and sectionFooterClass, will it make things better?

**Comment by kafejo** [comment]
I agree.
